djangopermissions/djangopermissions/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.Userlogin,name ='login'),
    path('logout/', views.UserLogout,name ='logout'),
    path('signup/', views.UserRegistration,name ='singup'),
    path('create/', views.Create,name ='create'),
    path('viewpost/', views.ViewPost,name ='viewpost'),
    path('home/', views.HomeView,name ='home'),
    path('profile/', views.userprofile,name ='profile'),
    path('sucess/', views.registersuccesfull,name ='success'),

]

djangopermissions/myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.utils import timezone 
from django.contrib.auth.models import User


class Article(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()

	def __str__(self):
		return self.title




 

djangopermissions/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import Article

class SignupUser(UserCreationForm):
	first_name = forms.CharField(max_length=100,required = True)
	last_name =  forms.CharField(max_length=100,required = True)
	email = forms.EmailField(max_length=250)

	class Meta:
		model = User
		fields = ('username','first_name','last_name','email','password1','password2',)

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class PostCreate(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

djangopermissions/myapp/views.py
from django.shortcuts import render,redirect
from .models import Article
from .forms import UserLoginForm,PostCreate,SignupUser
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User,Permission
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType

def Userlogin(request):
	if request.method == 'POST':
		loginForm = UserLoginForm(request.POST or None)
		if loginForm.is_valid():
			username = loginForm.cleaned_data.get('username')
			password = loginForm.cleaned_data.get('password')
			user = authenticate(username=username,password=password)
			if user.is_active:
				login(request,user)
				return redirect(HomeView)
	else:
		loginForm = UserLoginForm()
	return render(request,'login.html',{'loginForm':loginForm})

def UserRegistration(request):
	if request.method == 'POST':
		UserRegister = SignupUser(request.POST or None)
		if UserRegister.is_valid():
			UserRegister.save()
			username = UserRegister.cleaned_data.get('username')
			password = UserRegister.cleaned_data.get('password')
			user = authenticate(username=username,password=password)
			return redirect(registersuccesfull)
	else:
		UserRegister = SignupUser()
	return render(request,'signup.html',{'UserRegister':UserRegister})

@login_required
def UserLogout(request):
	logout(request)
	return redirect(Userlogin)

def registersuccesfull(request):
	return render(request,'success.html')

@login_required
def userprofile(request,pk=None):
	if pk:
		user = User.objects.get(pk=pk)
		if (user == User.objects.get(username='anil')):
			user.has_perm('myapp.view_Article')
	else:
		user = request.user
	print(user)
	return render(request,'userprofile.html',{'user':user})

@login_required
def HomeView(request):
	return render(request,'home.html')

@login_required
def Create(request):
	if request.method == 'POST':
		postform = PostCreate(request.POST or None)
		if postform.is_valid():
			postform.save()
			redirect(ViewPost)
	else:
		postform = PostCreate()
	return render(request,'create.html',{'postform':postform})

@login_required
def ViewPost(request):
	post = Article.objects.all()
	return render(request,'viewpost.html',{'post':post})


	


djangopermissions/templates/create.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<form method="post">
	{% csrf_token %}
	{{postform.as_p}}
	<button type="submit">Submit</button>
	<button><a href="{% url 'home' %}">Back</a></button>
</form>
</body>
</html>

djangopermissions/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>
<button><a href="{% url 'profile' %}">Profile</a></button>
<button><a href="{% url 'logout' %}">Logout</a></button>
<button><a href="{% url 'create' %}">Create Post</a></button>
<button><a href="{% url 'viewpost' %}">View post</a></button>
</body>
</html>

djangopermissions/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>
<form method="post">
	{% csrf_token%}
	{{loginForm.as_p}}
	<button type="submit">Submit</button>
	<button type="submit"><a href="{% url 'singup' %}">New user</a></button>
</form>
</body>
</html>

djangopermissions/templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>Signup</title>
</head>
<body>
	<form method="post">

    {% csrf_token %}
	{{UserRegister.as_p}}

	<button type="submit">Submit</button>
	<button type="submit"><a href="{% url 'login' %}">Login</a></button>
</form>
</body>
</html>

djangopermissions/templates/success.html
<!DOCTYPE html>
<html>
<head>
	<title>succesfull</title>
</head>
<body>
<h2>Signup succesfull</h2>
</body>
</html>

djangopermissions/templates/userprofile.html
<!DOCTYPE html>
<html>
<head>
	<title>profile</title>
</head>
<body>
	<label>Username = </label>{{user}}<br>
	<label>First name = </label>{{user.first_name}}<br>
	<label>Last name = </label>{{user.last_name}}<br>
	<label>Mail = </label>{{user.email}}<br>

	<!-- To view permissions the user have use the
		following command-->

		<div>{{ perms.myapp }}</div>
		<button><a href="{% url 'home'%}">Back</a></button>
	</body>
</html>

djangopermissions/templates/viewpost.html
<!DOCTYPE html>
<html>
<head>
	<title>Post View</title>
</head>
<body>
	


<!--<div>{{ perms.myapp }}</div>-->

{% if perms.myapp.view_article %}
{% for a in post %}

{{a.title}}<br>
{{a.description}}<br>
{% endfor %}
{% else %}
{{user.username}}
    <p>You don't have permission to do anything in the myapp.</p>



{% endif %}
<button><a href="{% url 'home'%}">Back</a></button>

</body>
</html>